### ISSUE TITLE
Syntax error while pasrsing `orctempel.zen`

### ISSUE THREAD

**Issue by thokkat** [GothicKit/phoenix#68]
Happens while parsing `Demon.mds`, no other files are affected. Catching and ignoring the error in OpenGothic is ok but wanted to report it in case something can be done to handle yet another Gothic file quirk.

`loading error: failed parsing resource of type model_script (source) [context: MDS syntax error at line 262 column 8: expected keyword] `

**Comment by lmichaelis** [comment]
Thanks for the report! It looks like the only problem was a single trailing semicolon. fee2dd1 should fix it :)

**Comment by thokkat** [comment]
Runs like a charm :)
