### ISSUE TITLE
Parse of "JustWhite" lighting preset resulting in wrong color

### ISSUE THREAD

**Issue by Try** [GothicKit/phoenix#69]
Here are values for `color_animation_list`:
`"255 (255 255 240) 255 (255 240 255) (240 255 255) 255 "`

I'm not 100% sure, but probably syntax is:
`(255 255 240)` = full rgb color
`255` = grayscale color

**Comment by lmichaelis** [comment]
Hi @Try, yeah I can see what you mean. I'll take a look at the decomp hopefully later this week. Thanks for the report.

**Comment by lmichaelis** [comment]
Yeah looks like you're right. I can't decipher everything with 100% accuracy but this code is run if no `'('`-char is found between two space chars in the input stream:

![bilde](https://github.com/GothicKit/phoenix/assets/20187490/c824b154-6b7f-47d3-99f2-2607726c549e)

`outColor.a` is initialized beforehand with `0xff` so this seems like the right thing. I've added a patch, could you please test if it does the right thing for you?

**Comment by Try** [comment]
Tested today: "JustWhite" works as expected
