### ISSUE TITLE
Parse of empty model-source

### ISSUE THREAD

**Issue by Try** [GothicKit/phoenix#70]
In `std::string buffer::get_line_and_ignore(std::string_view whitespace)` there is a bug:
Implementation expects to read at least single `char`, what breaks on empty sources.

Proposed fix:
```c++
std::string buffer::get_line_and_ignore(std::string_view whitespace) {
    std::string tmp {};

+  if(this->position()==this->limit())
+    return "";

   char c = this->get_char();
   ...
```

Found while testing L'Hiver English edition mod. Problematic model: draconian_swordsman.mdm

**Comment by lmichaelis** [comment]
Hi @Try, this is a known problem with all empty files at the moment. This should be a simple fix, expect a push by Sunday :)

**Comment by Try** [comment]
No rush :)
Since it's about mod, I'll publish OpenGothic update today anyways and fix will land into next release.

**Comment by Try** [comment]
Are you sure that https://github.com/GothicKit/phoenix/commit/ed37464ca1cbe55d3ce708b0454652c3bea89aec related to this issue?
`draconian_swordsman` file is not empty - a single block with model-source is.

**Comment by lmichaelis** [comment]
Oh, then I misunderstood the issue, sorry. Could you send over the file that's causing issues so I can investigate it (either here or in the GMC Discord — `@lmichaelis`)?

**Comment by Try** [comment]
Here is one of the problematic files
[Draconian_Shaman.zip](https://github.com/GothicKit/phoenix/files/11927686/Draconian_Shaman.zip)

**Comment by lmichaelis** [comment]
I've added what is essentially your solution. Could you please confirm?

**Comment by Try** [comment]
Tested today - works as expected
