### ISSUE TITLE
`Vfs::child` : Name comparison fails due to extra whitespace

### ISSUE THREAD

**Issue by thokkat** [GothicKit/phoenix#75]
Old german mod `Karibik` has the world `PINTA_GANG.ZEN` but the corresponding `trigger_change_level` has attribute `level_name="PINTA_GANG.ZEN "` with a trailing whitespace. When triggered in OpenGothic loading does not work because the extra whitespace makes the equality check fail in `Vfs::child`.

 Original Gothic works so it seems whitespaces are ignored there.

**Comment by lmichaelis** [comment]
Yes, that would be correct. Gothic has its own hand-rolled file path parsing implementation which fully parses paths passed into it and re-creates them again before opening a file. Potential fix: in `VfsNode::child` and `VfsNode::remove`, trim trailing whitespace from `name`.

**Comment by lmichaelis** [comment]
Could you verify if 9e8458ed fixes this issue, please?

**Comment by Elgcahlxukuth** [comment]
Not sure if this is the same bug, but I just noticed the file "OW_FIREDRAGON_ VOLCANO_03-C.TEX" would not be found within my  "Textures.vdf" archive of Gothic 2 NOTR, even though the file is there.

**Comment by thokkat** [comment]
Issue is gone, thanks.
