### ISSUE TITLE
Vfs: Node names may be cut off if the contain spaces

### ISSUE THREAD

**Issue by lmichaelis** [GothicKit/phoenix#77]
As noted by @Elgcahlxukuth in #75 ([link](https://github.com/GothicKit/phoenix/issues/75#issuecomment-1652138084)), Vfs nodes names parsed from `.vdf`-files are cut off at the first space char which breaks nodes with spaces in their names.

**Comment by lmichaelis** [comment]
Hey @Elgcahlxukuth can you check that this fix also works on your end (7e447c3)?

**Comment by Elgcahlxukuth** [comment]
> Hey @Elgcahlxukuth can you check that this fix also works on your end ([7e447c3](https://github.com/GothicKit/phoenix/commit/7e447c3e4964f94fc0c85ba2eb151dd42ed355e8))?

the fix is working 👍  good job!
